apiVersion: batch/v1
kind: CronJob
metadata: 
  name: data-processing-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: data-processing-container
            image: python:3.9-slim
            command: ["python","-c","import time; print('Starting data processing...'); time.sleep(10); print('Data processing finished.');"]
          restartPolicy: OnFailure
      backoffLimit: 4