apiVersion: apps/v1
kind: Deployment
metadata: 
  name: single-nginx-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.25.1
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata: 
  name: my-nginx-service

spec:
  selector:
    app: my-nginx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
